# Generated by Django 2.1.5 on 2019-02-13 13:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quack', '0002_auto_20190213_1024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quack',
            old_name='author',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_joined',
            field=models.DateField(default=datetime.datetime(2019, 2, 13, 13, 30, 4, 736704, tzinfo=utc)),
        ),
    ]
