# Generated by Django 2.1.5 on 2019-02-13 13:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quack', '0003_auto_20190213_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_joined',
            field=models.DateField(default=datetime.datetime(2019, 2, 13, 13, 47, 41, 637431, tzinfo=utc)),
        ),
    ]
