# Generated by Django 2.1.5 on 2019-02-14 06:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quack', '0005_auto_20190214_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_joined',
            field=models.DateField(default=datetime.datetime(2019, 2, 14, 6, 57, 59, 828481, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='quack',
            name='tags',
            field=models.CharField(max_length=100),
        ),
    ]
