# Generated by Django 2.1.5 on 2019-02-18 18:47

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quack', '0007_auto_20190214_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='quack',
            name='likes',
            field=models.ManyToManyField(related_name='fans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_joined',
            field=models.DateField(default=datetime.datetime(2019, 2, 18, 18, 47, 10, 191413)),
        ),
    ]
